#!/usr/bin/env node
// Snapshot every trip to a JSON file on the Pi.
//
//   node backup-trips.js
//   node backup-trips.js --dir /mnt/usb/ride-report --keep 24
//
// Reports are deliberately not backed up. They are derived data — a lost
// report is regenerated by the next scheduled run, and thirty days of them are
// pruned on purpose anyway. Trips are the only rows here that were typed by a
// person, which makes them the only rows worth a copy.
//
// This is the small end of the plan's two options. The other is a monthly
// `supabase db dump`, which captures more and needs the Postgres connection
// string rather than the REST key; see the README. Either is plenty at this
// scale, and the honest reason to prefer this one is that it runs on the
// machine that is already awake and already holds a key.

import { mkdir, readdir, readFile, writeFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

import { loadEnv, allTrips } from './db.js';

const DEFAULT_DIR = process.env.RIDE_BACKUP_DIR || path.join(os.homedir(), 'ride-report-backups');
const DEFAULT_KEEP = Number(process.env.RIDE_BACKUP_KEEP || 12);
const PREFIX = 'trips-';

function parseArgs(argv) {
  const args = { dir: DEFAULT_DIR, keep: DEFAULT_KEEP };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--dir') args.dir = argv[++i];
    else if (arg === '--keep') args.keep = Number(argv[++i]);
    else if (arg.startsWith('--dir=')) args.dir = arg.slice(6);
    else if (arg.startsWith('--keep=')) args.keep = Number(arg.slice(7));
  }
  return args;
}

/** Snapshot filenames, newest last. ISO stamps sort lexically, which is the point. */
async function existingSnapshots(dir) {
  try {
    const names = await readdir(dir);
    return names.filter((n) => n.startsWith(PREFIX) && n.endsWith('.json')).sort();
  } catch {
    return []; // no directory yet
  }
}

/**
 * The trips from the newest snapshot, or null if there isn't one to compare
 * against. A corrupt or half-written file reads as "no previous snapshot",
 * which errs toward writing an extra copy — the safe direction for a backup.
 */
async function previousTrips(dir, snapshots) {
  const newest = snapshots[snapshots.length - 1];
  if (!newest) return null;

  try {
    const parsed = JSON.parse(await readFile(path.join(dir, newest), 'utf8'));
    return Array.isArray(parsed.trips) ? parsed.trips : null;
  } catch {
    return null;
  }
}

async function main() {
  const { dir, keep } = parseArgs(process.argv.slice(2));
  await loadEnv();

  const trips = await allTrips();
  const snapshots = await existingSnapshots(dir);

  // Nothing changed since the last snapshot, so don't take another one. Without
  // this, a daily timer buries the handful of snapshots that differ under a
  // hundred that don't, and "when did that trip change?" stops being findable.
  const previous = await previousTrips(dir, snapshots);
  if (previous && JSON.stringify(previous) === JSON.stringify(trips)) {
    console.log(`[backup] ${trips.length} trip(s), unchanged since ${snapshots[snapshots.length - 1]} — nothing written`);
    return 0;
  }

  await mkdir(dir, { recursive: true });

  // Colons are legal on ext4 and a nuisance everywhere else, including on the
  // USB stick this eventually gets copied to.
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const file = path.join(dir, `${PREFIX}${stamp}.json`);

  await writeFile(file, `${JSON.stringify({ taken_at: new Date().toISOString(), trips }, null, 2)}\n`, {
    // The trips carry notes and destinations. Same reasoning as `chmod 600 .env`
    // — this is a personal file on a shared-ish machine.
    mode: 0o600,
  });
  console.log(`[backup] wrote ${trips.length} trip(s) to ${file}`);

  // Prune oldest-first, counting the file just written.
  const stale = [...snapshots, path.basename(file)].slice(0, -keep);
  for (const name of stale) {
    await unlink(path.join(dir, name));
    console.log(`[backup] pruned ${name}`);
  }

  return 0;
}

main()
  .then((code) => process.exit(code))
  .catch((err) => {
    console.error(`[backup] FAILED: ${err.message}`);
    if (process.env.DEBUG) console.error(err.stack);
    process.exit(1);
  });
